Repository googleapis/python-artifact-registry, pull requests merged in 2021-04, with the labels that each got.

#13 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#14 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: artifactregistry, cla: yes, context: full, samples

#17 chore: templates update
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#16 chore: prevent normalization of semver versioning
  setup.py
Labels: api: artifactregistry, automerge, cla: yes

#18 chore(revert): revert preventing normalization
  setup.py
Labels: api: artifactregistry, automerge, cla: yes
